export const PIC_REQUEST = "PIC_REQUEST";
export const PIC_REQUEST_SUCCESS = "PIC_REQUEST_SUCCESS";
export const PIC_REQUEST_FAILURE = "PIC_REQUEST_FAILURE";
export const PIC_FETCH = "PIC_FETCH";
export const PIC_DELETE = "PIC_DELETE";
