export const PICS_REQUEST = "PICS_REQUEST";
export const PICS_REQUEST_SUCCESS = "PICS_REQUEST_SUCCESS";
export const PICS_REQUEST_FAILURE = "PICS_REQUEST_FAILURE";
export const PICS_FETCH = "PICS_FETCH";
